name: Build and Push Docker Images

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual run'
        required: true
        default: 'Manual trigger'
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: mizpuno
          password: dckr_pat_ChJw8TImh9mnJx3L7U8j4lJWBLQ

       # The section below provides angular web-application.
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: mizpuno/pogaty-web-front
